<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>B站视频与图片展示</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', 'Microsoft YaHei', sans-serif;
        }
        
        body {
            background: linear-gradient(135deg, #f5f7fa 0%, #e4edf5 100%);
            color: #333;
            line-height: 1.6;
            padding: 20px;
            min-height: 100vh;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        
        header {
            text-align: center;
            margin-bottom: 40px;
            padding: 20px;
            animation: fadeInDown 1s ease;
        }
        
        h1 {
            font-size: 2.8rem;
            color: #0a7bff;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
        }
        
        .subtitle {
            font-size: 1.2rem;
            color: #666;
            max-width: 600px;
            margin: 0 auto;
        }
        
        .content-wrapper {
            display: flex;
            flex-wrap: wrap;
            gap: 30px;
            justify-content: center;
        }
        
        .video-section, .images-section {
            background: white;
            border-radius: 15px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            flex: 1;
            min-width: 300px;
            max-width: 600px;
        }
        
        .video-section:hover, .images-section:hover {
            transform: translateY(-10px);
            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.15);
        }
        
        .section-header {
            background: linear-gradient(90deg, #0a7bff, #00c6ff);
            color: white;
            padding: 15px 20px;
            font-size: 1.5rem;
            display: flex;
            align-items: center;
        }
        
        .section-header i {
            margin-right: 10px;
            font-size: 1.8rem;
        }
        
        .section-content {
            padding: 25px;
        }
        
        /* 视频容器样式 */
        .video-container {
            position: relative;
            padding-bottom: 56.25%; /* 16:9 宽高比 */
            height: 0;
            overflow: hidden;
            border-radius: 10px;
            background: #000;
            margin-bottom: 20px;
        }
        
        .video-container iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: none;
        }
        
        .video-info {
            padding: 10px 0;
        }
        
        .video-info h3 {
            color: #0a7bff;
            margin-bottom: 10px;
            font-size: 1.4rem;
        }
        
        /* 图片容器样式 */
        .image-card {
            margin-bottom: 30px;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);
            transition: all 0.3s ease;
        }
        
        .image-card:hover {
            transform: scale(1.02);
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.12);
        }
        
        .image-container {
            width: 100%;
            height: 300px;
            overflow: hidden;
            background-color: #f0f0f0;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #999;
            font-size: 1rem;
        }
        
        .image-description {
            padding: 20px;
            background: #f9f9f9;
            border-top: 1px solid #eee;
        }
        
        .image-description h3 {
            color: #ff6b6b;
            margin-bottom: 10px;
            font-size: 1.3rem;
        }
        
        .instructions {
            background: white;
            border-radius: 15px;
            padding: 25px;
            margin: 40px auto;
            max-width: 800px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        }
        
        .instructions h2 {
            color: #0a7bff;
            margin-bottom: 20px;
            text-align: center;
            font-size: 1.8rem;
        }
        
        .instruction-step {
            margin-bottom: 25px;
            padding: 20px;
            border-radius: 10px;
            background: #f8fbff;
            border-left: 4px solid #0a7bff;
        }
        
        .instruction-step h3 {
            color: #ff6b6b;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
        }
        
        .instruction-step h3 i {
            margin-right: 10px;
            font-size: 1.5rem;
        }
        
        footer {
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #666;
            font-size: 1rem;
        }
        
        /* 动画效果 */
        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .fadeInUp {
            animation: fadeInUp 1s ease;
        }
        
        /* 响应式设计 */
        @media (max-width: 768px) {
            .content-wrapper {
                flex-direction: column;
                align-items: center;
            }
            
            .video-section, .images-section {
                width: 100%;
                max-width: 100%;
            }
            
            h1 {
                font-size: 2.2rem;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1><i class="fas fa-play-circle"></i> B站视频与图片展示</h1>
            <p class="subtitle">展示您最喜爱的B站视频和精美图片，附带详细描述</p>
        </header>
        
        <div class="content-wrapper">
            <!-- 视频部分 -->
            <section class="video-section fadeInUp">
                <div class="section-header">
                    <i class="fab fa-bilibili"></i>
                    <h2>B站视频展示</h2>
                </div>
                <div class="section-content">
                    <div class="video-container">
                        <!-- 视频嵌入位置 -->
                        <iframe src="//player.bilibili.com/player.html?aid=113854214309949&bvid=BV1Fiwre7EpE&cid=27961787478&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
                    </div>
                    <div class="video-info">
                        <h3>【明日方舟新春会】灶里乾坤</h3>
                        <p>民以食为天，照拂天下烟火。</p>
                    </div>
                </div>
            </section>
            
            <!-- 图片部分 -->
            <section class="images-section fadeInUp">
                <div class="section-header">
                    <i class="fas fa-images"></i>
                    <h2>图片展示区</h2>
                </div>
                <div class="section-content">
                    <!-- 第一张图片 -->
                    <div class="image-card">
                        <div class="image-container">
                            <!-- 图片文件位置 -->
                            <img src="https://images.unsplash.com/photo-1501854140801-50d01698950b" alt="自然风景" style="width:100%;height:100%;object-fit:cover;">
                        </div>
                        <div class="image-description">
                            <h3><i class="fas fa-mountain"></i> 弹幕数量变化图</h3>
                            <p>5s一单位，统计弹幕数量变化</p>
                        </div>
                    </div>
                    
                    <!-- 第二张图片 -->
                    <div class="image-card">
                        <div class="image-container">
                            <!-- 图片文件位置 -->
                            <img src="https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05" alt="城市夜景" style="width:100%;height:100%;object-fit:cover;">
                        </div>
                        <div class="image-description">
                            <h3><i class="fas fa-city"></i> 弹幕文本词云图</h3>
                            <p>处理后数据导入微词云，以余主要配色生成词云图</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        
        <footer>
            <p>© 2025 python程序设计结课作业展示页面 | 使用HTML5和CSS3构建</p>
        </footer>
    </div>
</body>
</html>
